# ServiceMonitor for Istio Gateway (Envoy) metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-gateway-metrics
  namespace: openshift-ingress
  labels:
    app.kubernetes.io/part-of: maas-observability
spec:
  selector:
    matchLabels:
      app: istio-gateway-metrics
  endpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 15s


