---
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: latency-per-tier
  namespace: openshift-ingress
spec:
  selector:
    matchLabels:
      gateway.networking.k8s.io/gateway-name: maas-default-gateway
  metrics:
  - providers:
    - name: prometheus
    overrides:
    - match:
        metric: REQUEST_DURATION
        mode: CLIENT_AND_SERVER
      tagOverrides:
        tier:
          operation: UPSERT
          value: request.headers["x-maas-tier"]
