# Note: If Kuadrant CR has spec.observability.enable=true, the operator creates its
# own PodMonitor (kuadrant-limitador-monitor) that scrapes the same Limitador pod.
# In that case, do NOT deploy this ServiceMonitor to avoid duplicate metrics.
# This ServiceMonitor is only needed when Kuadrant observability is NOT enabled.
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: limitador-metrics
  namespace: kuadrant-system
  labels:
    app: limitador
spec:
  selector:
    matchLabels:
      app: limitador
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
