---
apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-realm-import
  namespace: keycloak-system
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: realm-import
        image: curlimages/curl:8.5.0
        command: ["/bin/sh"]
        args:
        - -c
        - |
          echo "Waiting for Keycloak to be ready..."
          until curl -s http://keycloak:8080/realms/master > /dev/null; do
            echo "Keycloak not ready, waiting..."
            sleep 10
          done
          
          echo "Getting admin token..."
          ADMIN_TOKEN=$(curl -s -X POST \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "username=admin&password=admin123&grant_type=password&client_id=admin-cli" \
            http://keycloak:8080/realms/master/protocol/openid-connect/token | \
            grep -o '"access_token":"[^"]*' | grep -o '[^"]*$')
          
          if [ -z "$ADMIN_TOKEN" ]; then
            echo "Failed to get admin token"
            exit 1
          fi
          
          echo "Creating maas realm..."
          curl -s -X POST \
            -H "Authorization: Bearer $ADMIN_TOKEN" \
            -H "Content-Type: application/json" \
            -d @/tmp/realm-config/maas-realm.json \
            http://keycloak:8080/admin/realms
          
          echo "Realm import completed"
        volumeMounts:
        - name: realm-config
          mountPath: /tmp/realm-config
      volumes:
      - name: realm-config
        configMap:
          name: maas-realm-config
