---
# OIDC-based Rate Limiting Policy
# This policy applies different rate limits based on user tier from JWT claims
apiVersion: kuadrant.io/v1
kind: RateLimitPolicy
metadata:
  name: gateway-rate-limits-oidc
  namespace: llm
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: inference-gateway
  limits:
    free-user-requests-oidc:
      rates:
        - limit: 5
          window: 2m
      when:
        - predicate: |
            auth.identity.tier == "free"
      counters:
        - expression: auth.identity.userid
    premium-user-requests-oidc:
      rates:
        - limit: 20
          window: 2m
      when:
        - predicate: |
            auth.identity.tier == "premium"
      counters:
        - expression: auth.identity.userid
    enterprise-user-requests-oidc:
      rates:
        - limit: 100
          window: 2m
      when:
        - predicate: |
            auth.identity.tier == "enterprise"
      counters:
        - expression: auth.identity.userid
