---
# ServiceAccounts for 3-tier access control testing
apiVersion: v1
kind: ServiceAccount
metadata:
  name: free-user
  namespace: maas-api
  labels:
    tier: free
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: premium-user
  namespace: maas-api
  labels:
    tier: premium
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: enterprise-user
  namespace: maas-api
  labels:
    tier: enterprise
