# Default Gateway Token Rate Limiting Policy
# NO LIMITS by default - simple deployment mode allows unlimited usage
# Teams can attach specific policies for budget/usage control
---
apiVersion: kuadrant.io/v1alpha1
kind: TokenRateLimitPolicy
metadata:
  name: gateway-default-unlimited
  namespace: llm
  labels:
    maas/resource-type: "default-rate-limit"
  annotations:
    maas/description: "Default unlimited rate policy - teams can override with specific limits"
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: inference-gateway
  limits:
    # Very high default limits = effectively unlimited
    # Teams with specific policies will override this for their users
    default-unlimited:
      rates:
        - limit: 999999999
          window: "1h"
      counters:
        - expression: "auth.identity.userid"
