# OpenShift Route for MaaS API Service
# Directs traffic from OpenShift router to Istio gateway
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: maas-api-route
  namespace: llm
  labels:
    app: maas-gateway
spec:
  host: maas-api.apps.summit-gpu.octo-emerging.redhataicoe.com
  port:
    targetPort: 80
  to:
    kind: Service
    name: inference-gateway-istio
    weight: 100
  wildcardPolicy: None
