apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: maas-kind-overlay

# Inherit base configuration
resources:
  # Namespaces (must be first)
  - namespaces.yaml

  # Core gateway routes and networking
  - ../../base/networking

  # Core MaaS API components
  - ../../base/maas-api

  # Policies
  - ../../base/policies

  # Gateway API resources (Kind-specific)
  - gateway-class.yaml
  - gateway-certificate.yaml

# Patches for Kind-specific customizations
patches:
  # Patch Gateway to use Istio GatewayClass and update namespace
  - target:
      kind: Gateway
      name: maas-default-gateway
    patch: |-
      - op: replace
        path: /metadata/name
        value: maas-gateway
      - op: replace
        path: /metadata/namespace
        value: maas-api
      - op: replace
        path: /spec/gatewayClassName
        value: istio
      - op: replace
        path: /spec/listeners/0/hostname
        value: localhost
      - op: replace
        path: /spec/listeners/1/hostname
        value: localhost

  # Patch HTTPRoute to point to the correct gateway and namespace
  - target:
      kind: HTTPRoute
      name: maas-api-route
    patch: |-
      - op: replace
        path: /spec/parentRefs/0/name
        value: maas-gateway
      - op: replace
        path: /spec/parentRefs/0/namespace
        value: maas-api
      - op: add
        path: /spec/hostnames
        value: ["localhost", "maas.local"]

  # Patch Gateway auth policy namespace
  - target:
      kind: AuthPolicy
      name: gateway-auth-policy
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: maas-api

  # Patch Gateway rate limit policies namespace
  - target:
      kind: RateLimitPolicy
      name: gateway-rate-limits
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: maas-api

  - target:
      kind: TokenRateLimitPolicy
      name: gateway-token-rate-limits
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: maas-api

  # Patch openshift-ai-inference Gateway (disable for Kind)
  - target:
      kind: Gateway
      name: openshift-ai-inference
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: maas-api

  # TODO: Add more patches as needed
  # - patch: |-
  #     apiVersion: apps/v1
  #     kind: Deployment
  #     metadata:
  #       name: maas-api
  #     spec:
  #       template:
  #         spec:
  #           containers:
  #           - name: maas-api
  #             env:
  #             - name: CLUSTER_DOMAIN
  #               value: "localhost"

# ConfigMap generators (if needed for Kind-specific config)
# configMapGenerator:
# - name: kind-config
#   literals:
#   - PLATFORM=kind
#   - CLUSTER_DOMAIN=localhost

# Images (pin to specific versions for stability)
# images:
# - name: quay.io/kuadrant/limitador
#   newTag: latest

# Labels to add to all resources
labels:
  - pairs:
      platform: kind
      environment: local-dev

# Annotations to add to all resources
commonAnnotations:
  managed-by: kustomize
  platform: kind
