version: "2"
run: 
  timeout: 8m
issues: 
  max-issues-per-linter: 0
  max-same-issues: 0
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - forbidigo
    - funlen
    - gochecknoglobals
    - gocognit
    - godox
    - gomoddirectives
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - paralleltest
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
    - funcorder
    - godoclint
    - noinlineerr
  settings:
    errcheck:
      check-type-assertions: true
    exhaustive:
      check:
        - switch
      default-signifies-exhaustive: true
    funlen:
      lines: 100
      statements: 100
      ignore-comments: true
    goconst:
      ignore-string-values:
        - "true"
        - "false"
    gocritic:
      enabled-checks:
        - deferInLoop
        - unnecessaryDefer
    gocyclo:
      min-complexity: 30
    importas:
      alias:       
        - pkg: k8s.io/api/(\w{1,4})\w*/(v[\w\d]+)
          alias: $1$2
        - pkg: github.com/openshift/api/(\w{1,4})\w*/(v[\w\d]+)
          alias: $1$2       
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - generic
    lll:
      line-length: 180
    nolintlint:
      require-specific: true
      allow-no-explanation:
        - funlen
        - lll
    perfsprint:
      sprintf1: false
      strconcat: false
    revive:
      rules:
        - name: dot-imports
          arguments:
            - allowedPackages:
                - github.com/onsi/ginkgo/v2
                - github.com/onsi/gomega
                - github.com/onsi/gomega/gstruct
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
        path: test/*/(.+)_test\.go
      - linters:
          - containedctx
        path: pkg/utils/test/testf/(.+)\.go
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/opendatahub-io/models-as-a-service/maas-api/)
        - blank
        - dot
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - api
      - third_party$
      - builtin$
      - examples$
